version: '3'
services:
  postgres:
    env_file: ./docker-env.env
    image: postgres
    restart: always
    ports:
      - '5000:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis
    restart: always
    ports:
      - '6379:6379'

volumes:
  pgdata:
    external: true
